# Use the official PowerShell image as the base
FROM mcr.microsoft.com/powershell:7.3.6-alpine-3.18

# Set the working directory
WORKDIR /app

# Copy the PowerShell server script into the container
COPY src/server.ps1 .

# Expose the port your server listens on
EXPOSE 8000

# Pass parameters to the PowerShell script
CMD ["pwsh", "-File", "server.ps1", "-port", "8000", "-rapidApiKey", "SIGN_UP_FREE_AND_SUBSCRIBE_TO_BOTH_APIS", "-hostPrefix", "http://+"]